name: Eslint Check

on:
  pull_request:
    types: [opened, synchronize] 
    branches:
      - branchname
jobs:
  linter-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 
        uses: actions/setup-node@v2 
        with: 
        node-version: '21.6.1' 
      - name: Install dependencies
        run: npm install
      - name: Linter action
        id: linter
        uses: AntonKornus/TypeScript-Linter@1.0.0
        with:
          folder: src